//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justin.BookShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCategory
    {
        public BookCategory()
        {
            this.Children = new HashSet<BookCategory>();
            this.Books = new HashSet<Book>();
            this.SpecialBooks = new HashSet<Book>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual PromotionInfo Promotion { get; set; }
        public virtual ICollection<BookCategory> Children { get; set; }
        public virtual BookCategory Parent { get; set; }
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<Book> SpecialBooks { get; set; }
    }
}
