//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justin.BookShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookStockHistory
    {
        public System.Guid ID { get; set; }
        public string Period { get; set; }
        public int PriorPeriodQuantity { get; set; }
        public decimal PriorPeriodMoney { get; set; }
        public int EntryQuantity { get; set; }
        public decimal EntryMoney { get; set; }
        public int OutQuantity { get; set; }
        public decimal OutMoney { get; set; }
        public int StocktakeQuantity { get; set; }
        public decimal StocktakeMoney { get; set; }
        public int DamagedQuantity { get; set; }
        public decimal DamagedMoney { get; set; }
        public decimal AdjustMoney { get; set; }
        public int ThisPeriodQuantity { get; set; }
        public decimal ThisPeriodMoney { get; set; }
    
        public virtual Book StockHistoryOf { get; set; }
    }
}
