//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justin.BookShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Sort = 0;
            this.Users = new HashSet<User>();
            this.Roles = new HashSet<UserRole>();
            this.Children = new HashSet<Department>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Sort { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<UserRole> Roles { get; set; }
        public virtual ICollection<Department> Children { get; set; }
        public virtual Department Parent { get; set; }
    }
}
