//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justin.BookShop.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesContainer : DbContext
    {
        public EntitiesContainer()
            : base("name=EntitiesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Book> Books { get; set; }
        public DbSet<BookComment> BookComments { get; set; }
        public DbSet<PromotionInfo> BookPromotionInfos { get; set; }
        public DbSet<BookCategory> Categories { get; set; }
        public DbSet<Author> Authors { get; set; }
        public DbSet<Press> Presses { get; set; }
        public DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public DbSet<CartItem> CartItems { get; set; }
        public DbSet<Order> Oders { get; set; }
        public DbSet<OrderItem> OderItems { get; set; }
        public DbSet<ReceiptInfo> ReceiptInfos { get; set; }
        public DbSet<OderTrace> OderTraces { get; set; }
        public DbSet<BookStock> BookStocks { get; set; }
        public DbSet<BookStockHistory> BookStockHistorys { get; set; }
        public DbSet<InStockReceipt> InStockReceipts { get; set; }
        public DbSet<InStockReceiptDetail> InStockReceiptDetails { get; set; }
        public DbSet<OutStockReceipt> OutStockReceipts { get; set; }
        public DbSet<OutStockReceiptDetail> OutStockReceiptDetails { get; set; }
        public DbSet<StocktakeReceipt> StocktakeReceipts { get; set; }
        public DbSet<StocktakeReceiptDeatil> StocktakeReceiptDeatils { get; set; }
        public DbSet<StockDamagedReceipt> StockDamagedReceipts { get; set; }
        public DbSet<StockDamagedReceiptDetail> StockDamagedReceiptDetailss { get; set; }
        public DbSet<PriceAdjustReceipt> PriceAdjustReceipts { get; set; }
        public DbSet<PriceAdjustReceiptDetail> PriceAdjustReceiptDetails { get; set; }
        public DbSet<SysVariable> SysVariables { get; set; }
        public DbSet<TraceInfo> TraceInfos { get; set; }
    }
}
