//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justin.BookShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InStockReceipt
    {
        public InStockReceipt()
        {
            this.IsAudited = false;
            this.Details = new HashSet<InStockReceiptDetail>();
        }
    
        public System.Guid ID { get; set; }
        public string NO { get; set; }
        public string PressNo { get; set; }
        public string Remark { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public bool IsAudited { get; set; }
        public int PressID { get; set; }
    
        public virtual Press Press { get; set; }
        public virtual User SubmittedBy { get; set; }
        public virtual User AuditedBy { get; set; }
        public virtual ICollection<InStockReceiptDetail> Details { get; set; }
        public virtual InStockReceipt InvalidReceipt { get; set; }
        public virtual InStockReceipt BeforeVoidReceipt { get; set; }
    }
}
