//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justin.BookShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OderTrace
    {
        public System.Guid ID { get; set; }
        public string Description { get; set; }
        public System.DateTime SubmitTime { get; set; }
        public System.Guid SubmittedUserID { get; set; }
        public System.Guid OrderID { get; set; }
    
        public virtual User SubmittedBy { get; set; }
        public virtual Order TraceOf { get; set; }
    }
}
