//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justin.BookShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.IsAudited = false;
            this.OrderItems = new HashSet<OrderItem>();
            this.Traces = new HashSet<OderTrace>();
            this.OutStockReceipts = new HashSet<OutStockReceipt>();
        }
    
        public System.Guid ID { get; set; }
        public string NO { get; set; }
        public decimal OrderPrice { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public OrderState State { get; set; }
        public decimal Freight { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public System.Guid ReceiptID { get; set; }
        public System.Guid UserID { get; set; }
        public bool IsAudited { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<System.Guid> AuditUserID { get; set; }
    
        public virtual User OrderOf { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ReceiptInfo Receipt { get; set; }
        public virtual ICollection<OderTrace> Traces { get; set; }
        public virtual ICollection<OutStockReceipt> OutStockReceipts { get; set; }
        public virtual User AuditedBy { get; set; }
    }
}
