//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justin.BookShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.Sort = 0;
            this.AuthorizedRoles = new HashSet<UserRole>();
            this.Children = new HashSet<Permission>();
            this.AuthorizedUsers = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string AlternateLink { get; set; }
        public PermissionType Type { get; set; }
        public string Description { get; set; }
        public int Sort { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<UserRole> AuthorizedRoles { get; set; }
        public virtual ICollection<Permission> Children { get; set; }
        public virtual Permission Parent { get; set; }
        public virtual ICollection<User> AuthorizedUsers { get; set; }
    }
}
