//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justin.BookShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionInfo
    {
        public PromotionInfo()
        {
            this.PromotionalBooks = new HashSet<Book>();
            this.PromotionalCategories = new HashSet<BookCategory>();
            this.PromotionalAuthors = new HashSet<Author>();
        }
    
        public System.Guid ID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Book> PromotionalBooks { get; set; }
        public virtual ICollection<BookCategory> PromotionalCategories { get; set; }
        public virtual ICollection<Author> PromotionalAuthors { get; set; }
    }
}
