//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justin.BookShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Gender = true;
            this.InUse = true;
            this.IsAdmin = false;
            this.Roles = new HashSet<UserRole>();
            this.BookComments = new HashSet<BookComment>();
            this.Orders = new HashSet<Order>();
            this.Receipts = new HashSet<ReceiptInfo>();
            this.SubmitedOderTraces = new HashSet<OderTrace>();
            this.SubmittedInStockReceipts = new HashSet<InStockReceipt>();
            this.AuditedInStockReceipts = new HashSet<InStockReceipt>();
            this.SubmittedOutStockReceipts = new HashSet<OutStockReceipt>();
            this.AuditedOutStockReceipts = new HashSet<OutStockReceipt>();
            this.SubmittedStocktakeReceipts = new HashSet<StocktakeReceipt>();
            this.AuditedStocktakeReceipts = new HashSet<StocktakeReceipt>();
            this.SubmittedStockDamagedReceipts = new HashSet<StockDamagedReceipt>();
            this.AuditedStockDamagedReceipts = new HashSet<StockDamagedReceipt>();
            this.SubmittedPriceAdjustReceipts = new HashSet<PriceAdjustReceipt>();
            this.AuditedPriceAdjustReceipts = new HashSet<PriceAdjustReceipt>();
            this.Permissions = new HashSet<Permission>();
            this.AuditedOrders = new HashSet<Order>();
        }
    
        public System.Guid ID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<bool> Married { get; set; }
        public string Phone { get; set; }
        public string Position { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Education { get; set; }
        public string School { get; set; }
        public bool InUse { get; set; }
        public System.DateTime AddedTime { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<EntityState> State { get; set; }
    
        public virtual ICollection<UserRole> Roles { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<BookComment> BookComments { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<ReceiptInfo> Receipts { get; set; }
        public virtual ICollection<OderTrace> SubmitedOderTraces { get; set; }
        public virtual ICollection<InStockReceipt> SubmittedInStockReceipts { get; set; }
        public virtual ICollection<InStockReceipt> AuditedInStockReceipts { get; set; }
        public virtual ICollection<OutStockReceipt> SubmittedOutStockReceipts { get; set; }
        public virtual ICollection<OutStockReceipt> AuditedOutStockReceipts { get; set; }
        public virtual ICollection<StocktakeReceipt> SubmittedStocktakeReceipts { get; set; }
        public virtual ICollection<StocktakeReceipt> AuditedStocktakeReceipts { get; set; }
        public virtual ICollection<StockDamagedReceipt> SubmittedStockDamagedReceipts { get; set; }
        public virtual ICollection<StockDamagedReceipt> AuditedStockDamagedReceipts { get; set; }
        public virtual ICollection<PriceAdjustReceipt> SubmittedPriceAdjustReceipts { get; set; }
        public virtual ICollection<PriceAdjustReceipt> AuditedPriceAdjustReceipts { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual ShoppingCart ShoppingCart { get; set; }
        public virtual ICollection<Order> AuditedOrders { get; set; }
        public virtual TraceInfo TraceInfo { get; set; }
    }
}
